# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Info Globo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Info Globo
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.0'
    pod 'KVNProgress'
end
